### ISSUE TITLE
Performance investigations

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/healthcare-api-dicom-fuse#18]
What transmission rate can dicomFuse handle for a single file?

How much memory/cpu does a single instance transfer require?

What transmission rate can be achieved if a user sends multiple parallel requests to DICOMfuse?

**Comment by arvgord** [comment]
I'm writing tests to measure these metrics.

> What transmission rate can dicomFuse handle for a single file?

Do you mean only uploading or transmission rate for downloading too?

**Comment by dzelemba** [comment]
Right now let's focus on uploading, but ideally downloading too.

**Comment by arvgord** [comment]
Hi, Dusan. I wrote performance tests and found bottleneck(fixed this) in the current implementation. I'll present the test results beginning of next week and I'll create PR with changes. But first, we need to review and merge PR created by Egor.

**Comment by arvgord** [comment]
## Performance investigations.
## Test stand:
* CPU - Core i5-7400
* SSD - M.2 Samsung 970 EVO Plus 250 GB 
* OS - Ubuntu 18.04 LTS

I wrote tests inside DICOMFuse so that a user can measure the performance(transfer rate) on his computer.
User can launch DICOMFuse in test mode using the following commands:
- `java -cp healthcare-api-dicom-fuse-X.Y.Z.jar com.google.dicomwebfuse.DicomFuseTest --help` to get help messages for tests.
- `java -cp healthcare-api-dicom-fuse-X.Y.Z.jar com.google.dicomwebfuse.DicomFuseTest [options]` to start DICOMFuse in test mode with options (instead of `java -jar healthcare-api-dicom-fuse-X.Y.Z.jar [options]` in normal mode).
> How much memory/cpu does a single instance transfer require?

I could not measure these metrics inside DICOMFuse, that's why I used [VisualVm](https://visualvm.github.io/) profiler. Java uses heap with the garbage collector, so I could not exactly measure memory usage(only heap size or used heap memory).
1) Memory and CPU load to upload a single file:
![MemoryAndCPULoadToUploadASingleFile](https://user-images.githubusercontent.com/39695947/65967357-ae74fb80-e48b-11e9-88eb-ad96e17da8e3.png)
The average CPU load is about 5%.
2) Memory and CPU load to upload 1000 1 mebibyte files using 5 threads:
![1mb1000files5threadsCPUload](https://user-images.githubusercontent.com/39695947/65967660-30652480-e48c-11e9-9788-1dfa037e00f7.png)
The average CPU load is about 10%.
I found using VisualVM profiler that the less file size the less the transfer rate. It happens because the upload thread waits for a response from the server after upload more than upload time. For 1 mebibyte file upload thread waits for about 45% of the upload time.
3) Upload and response latency for 1 mebibyte file for several requests:
![1mb1000files5threadsResponceLatency](https://user-images.githubusercontent.com/39695947/65970868-7c669800-e491-11e9-830a-18699ea98105.png)
4) Transfer rate for 1 mebibyte files using 1 and 5 threads:
![1mb1000files5threadsTest](https://user-images.githubusercontent.com/39695947/65971082-d10a1300-e491-11e9-8d32-99ee170d33b4.png)
To improve performance for small files, users should increase the number of threads. I did tests using 50 threads(extreme case).
5) Memory and CPU load to upload 1000 1 mebibyte files using 50 threads:
![1mb1000files50threadsCPUload](https://user-images.githubusercontent.com/39695947/65972409-fe57c080-e493-11e9-98b4-8dd4097f5686.png)
The average CPU load is about 35%.
6) Transfer rate for 1 mebibyte files using 1 and 50 threads:
![1mb1000files50threadsTest](https://user-images.githubusercontent.com/39695947/65972449-0dd70980-e494-11e9-9212-1711b7caed3f.png)
The bottleneck, in this case, is network throughput.
7) Memory and CPU load to upload 1000 20 mebibyte files using 5 threads:
![20mb1000files5threadsCPUload](https://user-images.githubusercontent.com/39695947/65976531-72956280-e49a-11e9-87c1-b0275ea79272.png)
The average CPU load is about 20%.
8) Upload and response latency for 20 mebibyte file:
![20mb1000files5threadsResponceLatency](https://user-images.githubusercontent.com/39695947/65976665-ad979600-e49a-11e9-9b31-4e0a2a8593a2.png)
9) Transfer rate for 20 mebibyte files using 1 and 5 threads:
![20mb1000files5threadsTest](https://user-images.githubusercontent.com/39695947/65976700-b9835800-e49a-11e9-9cef-11ac970c363d.png)
In this case, the transfer rate is greater because the file size is larger.
10) Memory and CPU load to upload 1000 20 mebibyte files using 50 threads:
![20mb1000files50threadsCPUload](https://user-images.githubusercontent.com/39695947/65976772-d91a8080-e49a-11e9-9aeb-de37568b0d43.png)
The average CPU load is about 25%.
11) Transfer rate for 20 mebibyte files using 1 and 50 threads:
![20mb1000files50threadsTest](https://user-images.githubusercontent.com/39695947/65976815-f3ecf500-e49a-11e9-8450-1d3689cf199e.png)
The bottleneck, in this case, is also network throughput.
## Resume:
Users should use more threads to improve performance for small files.

**Comment by arvgord** [comment]
You can play with the [prerelease version](https://github.com/arvgord/healthcare-api-dicom-fuse/releases/tag/1.0.3) from my [performance test branch](https://github.com/arvgord/healthcare-api-dicom-fuse/tree/feature/performance-tests). In this version, I improved performance and added tests to measure throughput.
I also tried to measure performance metrics in Windows, but face the [issue](https://github.com/billziss-gh/winfsp/issues/254) due to which tests did not work in Windows correctly(show better performance than real). That's why current tests work only for Linux, but performance has increased for all platforms. I'm trying to workaround this issue to accurately measure performance metrics in Windows.

**Comment by arvgord** [comment]
@dzelemba I'll create PR with these changes if you approve the current approach to measure the transfer rate.

**Comment by dzelemba** [comment]
Nice!

Few comments about the tests
  - In general it'd be better to do performance tests from a GCP VM running the same region as the Healthcare API to eliminate any local network effects
  - You can also run dicomFuse in one VM and the test in another VM to remove an CPU usage from the actual test that is sending traffic
  - there's a ton of info above which is great, but it makes it hard to understand what's going on without spending time to dive into it. A quick summary table would be very useful.
  - for measuring performance I'd lean towards measuring it outside the tool rather than inside it, this will give a more accurate end-to-end picture, this will hopefully solve the Windows issue as well.

So as a next step I'm fine reviewing any PRs that improve performance around the tool, but I'm less sure about PRs that add this test mode to the tool for performance investigations. Outputting some simple metrics to Stackdriver to track things like throughput and latency would be good so that users could have a dashboard that tracks performance. Creating a Wiki page summarizing some of these investigations so that users have an idea of what performance they can expect would also be great.

**Comment by arvgord** [comment]
> there's a ton of info above which is great, but it makes it hard to understand what's going on without spending time to dive into it. A quick summary table would be very useful.

### Test results in the table
| File size MiB | Download rate - 1 thread MiB/s | Upload rate - 1 thread MiB/s | Upload rate - 5 threads MiB/s | Upload rate - 50 threads MiB/s | Upload delay % | Response delay % |
| ------- | -------- | ------ | -------- | ------- | ------ | ----- |
| 0,99   | 1        | 0,5   | 3,59   | 21,74 | 55    | 45    |
| 20,84 | 10,18 | 6,91 | 18,61 | 22,37 | 86,3 | 13,7 |

You can see that the larger the file size, the higher the transfer rate. It depends on the response delay and users should use more threads for small files.

> for measuring performance I'd lean towards measuring it outside the tool rather than inside it, this will give a more accurate end-to-end picture, this will hopefully solve the Windows issue as well.

I implemented tests inside DICOMFuse for users who want to measure performance on their side. Inside these tests, I use the [copy method for files](https://github.com/arvgord/healthcare-api-dicom-fuse/blob/feature/performance-tests/src/main/java/com/google/dicomwebfuse/performancetest/PerformanceTest.java). If you want to measure only DICOMFuse performance using GCP I'll add.

**Comment by arvgord** [comment]
I've created a Wiki page with results.

**Comment by dzelemba** [comment]
Ok great, ya replacing those results with results from a GCP VM in the same region as the Healthcare API would be great to remove network effects as much as possible.

**Comment by dzelemba** [comment]
Have we been able to test performance on Windows yet?

**Comment by arvgord** [comment]
I'm testing DICOMFuse, but you can see the first [results](https://github.com/GoogleCloudPlatform/healthcare-api-dicom-fuse/wiki/DICOMFuse-performance-investigations). Performance has increased significantly.

**Comment by arvgord** [comment]
I've done performance tests for Windows. 
> Outputting some simple metrics to Stackdriver to track things like throughput and latency would be good so that users could have a dashboard that tracks performance.

When I ran DICOMFuse in cloud I could see simple metrics like CPU and Network Bytes by default.
![metrics](https://user-images.githubusercontent.com/39695947/67274530-d1bf2380-f4ea-11e9-8a87-0536d398882e.png)
It's enough? Or do you mean add Stackdriver metrics for local DICOMFuse instances?

**Comment by dzelemba** [comment]
I think this that is good for now! I'll close out this issue, thanks!

**Comment by arvgord** [comment]
Maybe I'll add the same performance test for Linux?

**Comment by dzelemba** [comment]
Sounds good.

**Comment by arvgord** [comment]
Done
