### ISSUE TITLE
Supported sharded directories

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/healthcare-api-dicom-fuse#24]
In order to get around the fact that we can't list 100s of thousands of studies in a single folder, DICOMfuse should support a --study_dir_sharding flag that specifies what level of nesting should be used and the size of each level.

0, 5000 - current behavior
1: 5000 - 1 level of nesting with 5k files in each folder
  - So under /dicomStore it would be
    - /1/ --> studies from 1 -> 5000
    - /2/ --> studies from 5000 -> 10000
    - ....
    - 5000/ -> studies from 24,995,000 -> 25,000,000

This is just an idea for now.

**Comment by pavertomato** [comment]
seems like this have conflict with #23 because if study not in folder /1/ it's means it's some where in 2..n 
@arvgord correct me if i'm wrong but as i remember source of limitation for studies in one folder is file managers like explorer and nautilus?   so may be we should add parameter to remove restriction for case if user works with dicomfuse only by command line or scripts?

**Comment by arvgord** [comment]
> correct me if i'm wrong but as i remember source of limitation for studies in one folder is file managers like explorer and nautilus?

Yes, with many results a file manager may freeze. But in a command line(search, listing etc), it works significantly better.

**Comment by dzelemba** [comment]
Even a command line tool would have some limit though right? We have DICOM stores will millions of images, so an ls would never work in this case I don't think. Happy to be proven wrong though.

Yes this is in conflict with #23. The idea is to support both modes. So if someone uses a flat directory structure they can still navigate to any study using the correct path, but won't be able to list past the first 5k in a directory listing. However, if someone uses a nested directory structure then #23 wouldn't apply.

**Comment by pavertomato** [comment]
>We have DICOM stores will millions of images, so an ls would never work in this case I don't think. Happy to be proven wrong though.

it's need to be tested, do we have any publicly available store(or store we can get access to?) to test it?

**Comment by dzelemba** [comment]
I've given you both access to one of my test datasets that has ~10M instances in it:

projects/dzelemba-test/locations/us-central1/datasets/test/dicomStores/bulk_import_10m

**Comment by pavertomato** [comment]
> I've given you both access to one of my test datasets that has ~10M instances in it:
> 
> projects/dzelemba-test/locations/us-central1/datasets/test/dicomStores/bulk_import_10m

i don't have access to project "dzelemba-test" only to "dzelemba-test-2"

**Comment by dzelemba** [comment]
Ah I only gave you access to the one DICOM store, but you need access to the entire dataset for DICOMfuse to work. Can you try again?

**Comment by pavertomato** [comment]
seems to work now, thanks
but if i request https://cloudresourcemanager.googleapis.com/v1/projects i can't find this project in list

**Comment by pavertomato** [comment]
>Even a command line tool would have some limit though right?.

well even if command line could work correctly with such amount of files in one folder i think we can't use this strategy, because requests with huge offset works extremely slow, for example response time for this request is 80-96 seconds(more than a minute)
`https://healthcare.googleapis.com/v1beta1/projects/dzelemba-test/locations/us-central1/datasets/test/dicomStores/bulk_import_10m/dicomWeb/studies/?limit=50&offset=1000000`
![image](https://user-images.githubusercontent.com/878990/64715377-8af10d80-d4ea-11e9-8246-b83ebbdde24f.png)

**Comment by dzelemba** [comment]
Yes it's expected that you wouldn't be able to list the project because I only have you DICOM Viewer on the Dataset, not the entire Project.

And ah yes good point...

Ok this feature as it's currently described probably doesn't make sense then. It's also not clear that someone would need this exact functionality, so I'll close this issue for now. Thanks for the investigation!
